### ISSUE TITLE
Require a method to specify a client key to go with the ca_certs client option

### ISSUE THREAD

**Issue by khyron4eva** [elastic/rally#277]
Currently, you can specify a set of CA certs for Rally to use when connecting to an ES cluster using syntax such as the following:

`--client-options="use_ssl:true,verify_certs:true,ca_certs:'/home/claudej/rally/cert.cer'"`

However, there does not appear to be a syntax to specify the client key and certificate. Running Rally against an SSL enabled ES cluster is currently impossible without being able to supply these 2 things.

**Comment by khyron4eva** [comment]
Forgot to tag @danielmitterdorfer. Please let me know if you need anything else.

**Comment by danielmitterdorfer** [comment]
I tried to reproduce your issue locally. Here are all concrete steps:

1. Install Elasticsearch 5.4.0
2. Install x-pack: `bin/elasticsearch-plugin install x-pack`
3. Configure SSL (as per the [x-pack documentation](https://www.elastic.co/guide/en/x-pack/current/ssl-tls.html)) with an "instance name" of "rally-node", an IP of "127.0.0.1" and the DNS name "io" (that's the name of my machine)
4. Adapt `elasticsearch.yml`:

```yml
node.name: rally-node

xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.http.ssl.enabled: true

xpack.ssl.key: /Users/daniel/.rally/benchmarks/distributions/elasticsearch-5.4.0/config/x-pack/rally-node/rally-node.key
xpack.ssl.certificate: /Users/daniel/.rally/benchmarks/distributions/elasticsearch-5.4.0/config/x-pack/rally-node/rally-node.crt
xpack.ssl.certificate_authorities: [ "/Users/daniel/.rally/benchmarks/distributions/elasticsearch-5.4.0/config/x-pack/ca/ca.crt" ] 
```

Then I started the node and ran the following benchmark which finished without any errors:

```
esrally --pipeline=benchmark-only --challenge=append-no-conflicts-index-only --test-mode --client-options="use_ssl:true,verify_certs:true,ca_certs:'/Users/daniel/.rally/benchmarks/distributions/elasticsearch-5.4.0/config/x-pack/ca/ca.crt',basic_auth_user:'elastic',basic_auth_password:'changeme'" --cluster-health=yellow
```
